import { test, expect } from '@playwright/test';

// Generated by codegen

// Manual test cases ported to playwright using Codegen.
// Using Swag Labs' saucedemo website


// TC-LOGIN-001: Verify that a user can log in with valid credentials and see the inventory page.
test('TC-LOGIN-001', async ({ page }) => {
  await page.goto('https://www.saucedemo.com/');
  await expect(page).toHaveURL('https://www.saucedemo.com/');
  await page.pause();
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('standard_user');
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').fill('secret_sauce');
  await page.locator('[data-test="login-button"]').click();
  await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html');
  await expect(page.getByText('Swag Labs')).toBeVisible();
  await expect(page.locator('[data-test="primary-header"]')).toContainText('Swag Labs');
  await expect(page.locator('[data-test="secondary-header"]')).toBeVisible();
  await expect(page.locator('[data-test="title"]')).toContainText('Products');
  await expect(page.locator('[data-test="item-4-img-link"]')).toBeVisible();
  await expect(page.locator('[data-test="inventory-item-description"]').first()).toBeVisible();
  await expect(page.locator('[data-test="item-0-img-link"]')).toBeVisible();
  await expect(page.locator('[data-test="inventory-item-description"]').nth(1)).toBeVisible();
  await expect(page.locator('[data-test="item-1-img-link"]')).toBeVisible();
  await expect(page.locator('[data-test="inventory-item-description"]').nth(2)).toBeVisible();
  await expect(page.locator('[data-test="item-5-img-link"]')).toBeVisible();
  await expect(page.locator('[data-test="inventory-item-description"]').nth(3)).toBeVisible();
  await expect(page.locator('[data-test="item-2-img-link"]')).toBeVisible();
  await expect(page.locator('[data-test="inventory-item-description"]').nth(4)).toBeVisible();
  await expect(page.locator('[data-test="item-3-img-link"]')).toBeVisible();
  await expect(page.locator('[data-test="inventory-item-description"]').nth(5)).toBeVisible();
  await page.pause();
});

// TC-LOGIN-002: Verify that a user cannot log in with invalid credentials and sees an error message.
test('TC-LOGIN-002, 003', async ({ page }) => {
  await page.goto('https://www.saucedemo.com/');
  await page.pause();
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('standard_user');
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').fill('asldkfjas');
  await page.locator('[data-test="login-button"]').click();
  await expect(page.locator('[data-test="error"]')).toBeVisible();
  await expect(page.locator('[data-test="error"]')).toContainText('Epic sadface: Username and password do not match any user in this service');
  await page.reload();
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('asdlfka');
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').fill('secret_sauce');
  await page.locator('[data-test="login-button"]').click();
  await expect(page.locator('[data-test="error"]')).toBeVisible();
  await expect(page.locator('[data-test="error"]')).toContainText('Epic sadface: Username and password do not match any user in this service');
  await page.pause();
});